### ISSUE TITLE
MAC addresses in the constants.java

### ISSUE THREAD

**Issue by bilalbinameer** [networkedsystemsIITB/SDN_LTE_EPC#4]
Should I change the MAC addresses in the constants.java 
And if I change so what should be the address as the default gateway in the setup has three MAC addresses and also the RAN has two MAC.

**Comment by rinku-shah** [comment]
Hi Bilal,
Sorry for the delayed reply.
To answer your query,  Yes. You should change MAC addresses in Constants.java
Default gateway address is the DGW interface that is connected to RAN(mostly eth1, but refer to ifconfig on DGW).
RAN will have only 1 external interface, the other one is used by the lxc container but connectivity amongst containers. Rather every container will have such additional interface for lxc, which in the config file connects to lxcbr0.

**Comment by bilalbinameer** [comment]
Thank you
