### ISSUE TITLE
error in run ran using make

### ISSUE THREAD

**Issue by hossam252009** [networkedsystemsIITB/SDN_LTE_EPC#6]
![screenshot from 2019-01-11 02-13-19](https://user-images.githubusercontent.com/47040531/51770547-2b0d3a00-20b4-11e9-83fe-73ea30ab0cfb.png)
this is the error shown what is the problem?

**Comment by mythilivutukuru** [comment]
My students says you have not installed the ssl dependencies, also maybe the OS version could be a mismatch (in case dependencies are installed)

**Comment by hossam252009** [comment]
i currently installed ssl 1.1.0g but the OS is 18.04 . it does not work in any version just in 14.04?
