### ISSUE TITLE
oracle java8

### ISSUE THREAD

**Issue by hossam252009** [networkedsystemsIITB/SDN_LTE_EPC#9]
oracle java8 is currently unavailable

**Comment by WindyCitySDR** [comment]
Hello,

Here are the deb files for Oracle java8 Ubuntu Linux installers which should be appropriate per the ReadMe

Oracle-java8-installer Download for Linux (deb, all)

Download oracle-java8-installer linux packages for DEB Universal.

https://pkgs.org/download/oracle-java8-installer

**Comment by hossam252009** [comment]
thank you
